import { IFieldType, IOptionType } from "./types";

export const inputTypes: IOptionType[] = [
  { name: "متن کوتاه", value: "text" },
  { name: "متن طولانی", value: "textarea" },
  { name: "عدد", value: "number" },
  { name: "ایمیل", value: "email" },
  { name: "آپلودر عکس", value: "imageUploader" },
  { name: "آپلودر فایل", value: "fileUploader" },
  { name: "شماره تلفن", value: "tel" },
  { name: "چند گزینه ای چند انتخابی", value: "checkbox" },
  { name: "چند گزینه ای تک انتخابی", value: "radio" },
  { name: "سلکشن", value: "select" },
  { name: "URL", value: "url" },
  { name: "تقویم", value: "date" },
  { name: "سرچ", value: "search" },
  { name: "پسورد", value: "password" },
  { name: "کد ملی", value: "nationalCode" },
];

export const initialFields: IFieldType[] = [
  {
    label: "نام",
    name: "name",
    type: { name: "متن کوتاه", value: "text" },
    required: true,
    min: 2,
    max: 10,
    pattern: /^[A-Za-zآ-ی]+$/,
    pattenErrorMessage: ".لطفا فقط از حروف الفبا استفاده کنید",
    id: 0,
    options: [{ name: "کد ملی", value: "nationalCode" }],
  },
  {
    label: "نام خانوادگی",
    name: "familyName",
    type: { name: "متن کوتاه", value: "text" },
    required: false,
    min: 2,
    max: 10,
    pattern: undefined,
    pattenErrorMessage: undefined,
    id: 1,
    options: [{ name: "کد ملی", value: "nationalCode" }],
  },
  {
    label: "ایمیل",
    name: "email",
    type: { name: "ایمیل", value: "email" },
    required: true,
    pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$/,
    pattenErrorMessage: "این متن درست نمی باشد.",
    id: 2,
    options: [{ name: "کد ملی", value: "nationalCode" }],
    min: 8,
    max: 16,
  },
  {
    label: "پسورد",
    name: "password",
    type: { name: "پسورد", value: "password" },
    required: true,
    pattern: /^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%^&*(),.?":{}|<>]).*$/,
    pattenErrorMessage:
      "پسورد باید حداقل شامل یک حرف انگلیسی، یک عدد و یک کاراکتر خاص باشد.",
    min: 8,
    max: 16,
    id: 3,
    options: [{ name: "کد ملی", value: "nationalCode" }],
  },
  {
    label: "کد ملی",
    name: "nationalCode",
    type: { name: "کد ملی", value: "nationalCode" },
    required: false,
    pattern: /^9\d{9}$/,
    pattenErrorMessage:
      "لطفاً یک شماره تلفن معتبر وارد کنید (باید با 9 شروع شود و 10 رقم باشد).",
    id: 4,
    options: [{ name: "کد ملی", value: "nationalCode" }],
    min: 8,
    max: 16,
  },
  {
    label: "aaaa",
    name: "aaaa",
    type: { name: "کد ملی", value: "nationalCode" },
    required: false,
    pattern: undefined,
    pattenErrorMessage: undefined,
    id: 5,
    options: [{ name: "کد ملی", value: "nationalCode" }],
    min: undefined,
    max: undefined,
  },
  // {
  //   label: "bbbb",
  //   name: "bbbb",
  //   type: { name: "کد ملی", value: "nationalCode" },
  //   required: false,
  //   pattern: undefined,
  //   pattenErrorMessage: undefined,
  //   id: 6,
  //   options: [{ name: "کد ملی", value: "nationalCode" }],
  //   min: undefined,
  //   max: undefined,
  // },
];
