import { FormCategories, IFieldType, IOptionType } from "./types";

export const inputTypes: IOptionType[] = [
  { name: "متن کوتاه", value: "text" },
  { name: "متن طولانی", value: "textarea" },
  { name: "عدد", value: "number" },
  { name: "ایمیل", value: "email" },
  { name: "آپلودر عکس", value: "imageUploader" },
  { name: "آپلودر فایل", value: "fileUploader" },
  { name: "شماره تلفن", value: "tel" },
  { name: "چند گزینه ای چند انتخابی", value: "checkbox" },
  { name: "چند گزینه ای تک انتخابی", value: "radio" },
  { name: "سلکشن", value: "select" },
  { name: "URL", value: "url" },
  { name: "تقویم", value: "date" },
  { name: "سرچ", value: "search" },
  { name: "پسورد", value: "password" },
  { name: "کد ملی", value: "nationalCode" },
];

const initialPersonFields: IFieldType[] = [
  {
    label: "نام",
    name: "name",
    type: { name: "متن کوتاه", value: "text" },
    required: true,
    min: 2,
    max: 10,
    pattern: /^[A-Za-zآ-ی]+$/,
    patternErrorMessage: ".لطفا فقط از حروف الفبا استفاده کنید",
    id: 0,
    options: undefined,
    category: "person",
  },
  {
    label: "نام خانوادگی",
    name: "familyName",
    type: { name: "متن کوتاه", value: "text" },
    required: false,
    min: 2,
    max: 10,
    pattern: /^[A-Za-zآ-ی]+$/,
    patternErrorMessage: ".لطفا فقط از حروف الفبا استفاده کنید",
    id: 1,
    options: undefined,
    category: "person",
  },
  {
    label: "شماره تلفن",
    name: "phoneNumber",
    type: { name: "شماره تلفن", value: "tel" },
    required: true,
    pattern: /^9\d{9}$/,
    patternErrorMessage:
      "لطفاً یک شماره تلفن معتبر وارد کنید (باید با 9 شروع شود و 10 رقم باشد).",
    id: 2,
    options: undefined,
    min: undefined,
    max: undefined,
    category: "person",
  },
  {
    label: "ایمیل",
    name: "email",
    type: { name: "ایمیل", value: "email" },
    required: true,
    pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$/,
    patternErrorMessage: "ایمیل معتبر نمی باشد.",
    id: 3,
    options: undefined,
    min: undefined,
    max: undefined,
    category: "person",
  },
  {
    label: "کد ملی",
    name: "nationalCode",
    type: { name: "کد ملی", value: "nationalCode" },
    required: false,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 4,
    options: undefined,
    min: undefined,
    max: undefined,
    category: "person",
  },
  {
    label: "سن",
    name: "age",
    type: { name: "عدد", value: "number" },
    required: false,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 5,
    options: undefined,
    min: undefined,
    max: undefined,
    category: "person",
  },
  {
    label: "جنسیت",
    name: "gender",
    type: { name: "سلکشن", value: "select" },
    required: true,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 6,
    options: [
      { name: "مرد", value: "male" },
      { name: "زن", value: "female" },
    ],
    min: undefined,
    max: undefined,
    category: "person",
  },
];

const initialJobFields: IFieldType[] = [
  {
    label: "نام کسب و کار",
    name: "jobName",
    type: { name: "متن کوتاه", value: "text" },
    required: true,
    min: 2,
    max: 80,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 7,
    options: undefined,
    category: "job",
  },
  {
    label: "شعار کسب و کار",
    name: "slogan",
    type: { name: "متن کوتاه", value: "text" },
    required: false,
    min: 2,
    max: 80,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 8,
    options: undefined,
    category: "job",
  },
  {
    label: "نوع خدمات درخواستی",
    name: "radio",
    type: { name: "چند گزینه ای تک انتخابی", value: "radio" },
    required: true,
    min: undefined,
    max: undefined,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 9,
    options: [
      { name: "پشتیبانی 2 ماهه", value: "2" },
      { name: "پشتیبانی 6 ماهه", value: "6" },
    ],
    category: "job",
  },
  {
    label: "نوع خدمات درخواستی",
    name: "checkbox",
    type: { name: "چند گزینه ای چند انتخابی", value: "checkbox" },
    required: false,
    min: undefined,
    max: undefined,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 10,
    options: [
      { name: "پشتیبانی 2 ماهه", value: "2" },
      { name: "پشتیبانی 6 ماهه", value: "6" },
    ],
    category: "job",
  },
  {
    label: "لوگو",
    name: "imageUploader",
    type: { name: "آپلودر عکس", value: "imageUploader" },
    required: true,
    min: undefined,
    max: 4,
    pattern: /image\/(jpeg|png|gif|bmp|tiff|webp)/,
    patternErrorMessage: undefined,
    id: 11,
    options: undefined,
    category: "job",
  },
  {
    label: "آپلودر فایل",
    name: "fileUploader",
    type: { name: "آپلودر فایل", value: "fileUploader" },
    required: true,
    min: undefined,
    max: 4,
    pattern: /(\.pdf|\.docx|\.xlsx|\.txt|\.ppt|\.pptx)$/i,
    patternErrorMessage: undefined,
    id: 12,
    options: undefined,
    category: "job",
  },
];

const initialAccountFields: IFieldType[] = [
  {
    label: "نام کاربری",
    name: "userName",
    type: { name: "متن کوتاه", value: "text" },
    required: true,
    min: 2,
    max: 10,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 13,
    options: undefined,
    category: "account",
  },
  {
    label: "رمز عبور",
    name: "password",
    type: { name: "پسورد", value: "password" },
    required: true,
    pattern: /^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%^&*(),.?":{}|<>]).*$/,
    patternErrorMessage:
      "پسورد باید حداقل شامل یک حرف انگلیسی، یک عدد و یک کاراکتر خاص باشد.",
    min: 8,
    max: 16,
    id: 14,
    options: undefined,
    category: "account",
  },
  {
    label: "تکرار رمز عبور",
    name: "passwordRepeat",
    type: { name: "پسورد", value: "password" },
    required: true,
    pattern: /^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%^&*(),.?":{}|<>]).*$/,
    patternErrorMessage:
      "پسورد باید حداقل شامل یک حرف انگلیسی، یک عدد و یک کاراکتر خاص باشد.",
    min: 8,
    max: 16,
    id: 15,
    options: undefined,
    category: "account",
  },
];

const initialOthersFields: IFieldType[] = [
  {
    label: "توضیحات",
    name: "description",
    type: { name: "متن طولانی", value: "textarea" },
    required: true,
    min: 2,
    max: 100,
    pattern: undefined,
    patternErrorMessage: undefined,
    id: 16,
    options: undefined,
    category: "others",
  },
];

export const formCategories: FormCategories = {
  personFields: initialPersonFields,
  jobFields: initialJobFields,
  accountFields: initialAccountFields,
  othersFields: initialOthersFields,
};
